name: Check links in README.md

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: docker://dkhamsing/awesome_bot:latest
      with:
        args: /github/workspace/README.md --request-delay 1 --allow 502,503,504,509,521 --allow-dupe --allow-redirect --white-list https://ipfs.io,slideshare,https://img.shields.io,https://codeclimate.com/github/unixorn/works-with-home-assistant,https://www.concourse.ci,https://smile.amazon.com,https://inovelli.com/black-series-dimmer-switch-z-wave